# https://docs.vale.sh/topics/.vale.ini

MinAlertLevel = suggestion

IgnoredScopes = frontmatter, code
SkippedScopes = blockquote

[*.md]
BasedOnStyles = Vale, RedHat, proselint, write-good

; Personal preference
RedHat.Definitions = NO
RedHat.GitLinks = NO
RedHat.Headings = NO
RedHat.NoGerundsInTitles = NO
RedHat.PascalCamelCase = NO
RedHat.ReadabilityGrade = NO

; Prefer natural voice
RedHat.Contractions = NO
write-good.E-Prime = NO

; Prefer `typos`
RedHat.Spelling = NO
Vale.Spelling = NO

[CHANGELOG.md]
BasedOnStyles =

