# https://doc.rust-lang.org/clippy/lint_configuration.html
msrv = "1.85"

# API
allow-renamed-params-for = []
avoid-breaking-exported-api = false
check-private-items = true

# Style
enforce-iter-loop-reborrow = true

# Tests
allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
allow-unwrap-in-tests = true

# Types
disallowed-types = []

# Methods
disallowed-methods = []

# Macros
disallowed-macros = []
