# https://doc.rust-lang.org/cargo/reference/config.html

# https://doc.rust-lang.org/cargo/reference/profiles.html#dev
[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
debug = false

[profile.dev.build-override]
opt-level = 3

# https://doc.rust-lang.org/cargo/reference/profiles.html#release
[profile.release]
debug = "limited"
lto = "thin"
split-debuginfo = "packed"
strip = "debuginfo"

# https://doc.rust-lang.org/cargo/reference/profiles.html#custom-profiles
[profile.profiling]
inherits = "release"
debug = true
