name: Renovate

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # weekly

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

permissions: {}

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write # renovate
      pull-requests: read # renovate
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Renovate
        uses: renovatebot/github-action@316d7cd859606d6039a2182b7d69199e9b036835 # v46.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
