name: Renovate

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # weekly

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

permissions: {}

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    permissions:
      contents: read # checkout
      issues: write # renovate
      pull-requests: read # renovate
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Renovate
        uses: renovatebot/github-action@5402b206248e5a8c8427a15102702eb9c1793efc # v46.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
